test: 
  - select_sales_by_customer.sql
  - basic_join.sql
  - selective_join.sql
  - count_sales_by_customer.sql
  - count_sales.sql
  - count_customers.sql
  - count_sales_by_product.sql
  - count_customer_id_sales.sql
  - read_all_sales.sql
  - join_on_customerid.sql
