[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/fd/1
loglevel=info
logfile_maxbytes=0
logfile_backups=0
childlogdir=/tmp

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:init-services]
command=%(ENV_INSTALL_DIR)s/helpers/init-services.sh
directory=%(ENV_INSTALL_DIR)s
user=root                  ; or another user
autostart=true            ; start at supervisord startup
autorestart=false          ; don't restart when it exits
startretries=0             ; don't loop if it exits quickly
startsecs=0                ; consider it started immediately (OK to exit right away)
exitcodes=0                ; treat 0 as a successful run
stdout_logfile=/var/log/supervisor/%(program_name)s.out.log
stderr_logfile=/var/log/supervisor/%(program_name)s.err.log
priority=10

[include]
files = /etc/supervisor/conf.d/*.conf
        /etc/fdw/conf.d/*.conf