- name: Setup Springtail CI Environment
  hosts: localhost
  become: true
  roles:
    - role: common
      install_additional_packages: false
      install_aws_cli: false
    - role: python
    - role: custom-pg
    - role: postgres-config
    - role: user_dev
    - role: redis
    - role: entrypoint