- name: Setup Springtail CI Environment
  hosts: localhost
  become: true
  roles:
    - common
    - awscli
    - python
    - custom-pg
    - postgres-config
    - user_dev
    - redis
    - entrypoint