FROM python:3.13.7-trixie AS builder

WORKDIR /app
RUN apt-get update && apt-get install -y build-essential libpq-dev curl unzip python3-dev
COPY ./python/controller/requirements.txt .
RUN pip install --prefix=/install -r requirements.txt
COPY ./python/ .

FROM python:3.13.7-slim-trixie AS runtime
RUN apt-get update && apt-get install -y curl jq vim unzip postgresql-client
COPY --from=builder /install /usr/local
COPY --from=builder /app /app
COPY ./prod.system.settings.json /etc/default-system-settings.json
COPY scripts /app/scripts
WORKDIR /app