listen_addresses = '*'
ssl = on
ssl_cert_file = '/var/lib/postgresql/data/server.crt'
ssl_key_file  = '/var/lib/postgresql/data/server.key'
ssl_ca_file = '/var/lib/postgresql/data/root.crt'

wal_level = logical
max_wal_senders = 10
max_replication_slots = 10
max_connections = 100
max_prepared_transactions= 64