listen_addresses = '*'
ssl = off
ssl_cert_file = '/certs/server.crt'
ssl_key_file  = '/certs/server.key'
ssl_ca_file = '/certs/root.crt'

wal_level = logical
max_wal_senders = 10
max_replication_slots = 10
max_connections = 100
max_prepared_transactions= 64