system_json_path: '../../system.json.test'

# Number of schemas to create
num_schemas: 10

# Table configuration
table_configuration:
  # Number of tables per schema
  num_tables: 10
  # Number of columns per table (range)
  min_columns: 3
  max_columns: 10

# Index configuration
index_configuration:
  # Number of indexes per table (range)
  min_indexes: 0
  max_indexes: 2
  # Number of columns per index (range)
  min_columns_per_index: 1
  max_columns_per_index: 2

# Load configuration
load_configuration:
  # Number of inserts per table
  num_inserts: 500
  # Number of updates per table
  num_updates: 250
  # Number of deletes per table
  num_deletes: 125
  # Whether to allow nulls in the data for inserts
  allow_nulls:
    rows: true
    cols: true

# Whether to batch inserts
batched_inserts: false

# Operations to perform
operations: ['create_table', 'create_index', 'insert_data', 'update_data', 'delete_data']

# Whether to use the previous configuration to load tables
use_existing_config: false

file_configuration:
  output_files:
    # Query info generated by the load_generator script
    query_info: '/tmp/query_info.csv'
    # Final report
    final_report: '/tmp/final_report.xlsx'
    # Final traces - Raw trace data
    final_traces: '/tmp/final_traces.csv'
    # Final aggregates
    final_aggregates: '/tmp/final_aggregates.csv'

  meta_files:
    # Run configuration
    run_config: '/tmp/run_config.csv'
    # SQL generated by the load_generator script
    load_sql: '/tmp/load.sql'
    # Table columns
    table_columns: '/tmp/table_columns.json'
    # Table columns
    table_columns_csv: '/tmp/table_columns.csv'

  temporary_files:
    # XID traces
    xid_traces: '/tmp/xid_traces.csv'
    # PG-XID traces
    pgxid_traces: '/tmp/pgxid_traces.csv'
    # XID to PG-XID mapping
    xid_pgxid_mapping: '/tmp/xid_pgxid_mapping.csv'
    # Merged traces
    merged_traces: '/tmp/merged_traces.csv'
    # PG-XID summary
    pg_xid_summary: '/tmp/pg_xid_summary.csv'
