#!/bin/bash

# this script is for generating initial set of client and server certificates
# including self-signed certificate for root CA and intermediate certificate for
# intermediaate CA.

config_dir=$1
if [ -z "${config_dir}" ]; then
    config_dir="./config"
fi

echo "Config dir = ${config_dir}"

mkdir -p ${config_dir}/root_ca/requests
mkdir -p ${config_dir}/root_ca/new_certs
mkdir -p ${config_dir}/intermediate_ca/requests
mkdir -p ${config_dir}/intermediate_ca/new_certs
mkdir -p ${config_dir}/leaf

cat > ${config_dir}/ca.ext << EOF
[ default ]
basicConstraints = critical,CA:true     # recommended to be marked critical. required for a ca
keyUsage         = critical,keyCertSign # required to be marked critical. required for signing certs
EOF

root_req_config_file=${config_dir}/root_ca/root_req.config
cat > ${root_req_config_file} << EOF
[ req ]
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
countryName = US
commonName  = Springtail Test Root CA, springtail.io
C = US
ST = CA
L = San Francisco
O = Springtail Inc.
EOF

root_config_file=${config_dir}/root_ca/root.config
cat > ${config_dir}/root_ca/root.config << EOF
[ ca ]
default_ca      = CA_default

[ CA_default]
dir             = ${config_dir}/root_ca/  # helper variable pointing to ca specific files
database        = \$dir/index     # database of certs generated by the ca
new_certs_dir   = \$dir/new_certs/             # one dir up to make the demo easier
certificate     = \$dir/root.pem     # one dir up to make the demo easier
serial          = \$dir/serial    # file with incrementing hex serial number for certs
private_key     = \$dir/root.key

policy          = policy_any
email_in_dn     = no             # recommended
unique_subject  = no             # recommended for easier certificate rollover
copy_extensions = none           # don't honor the extensions in the csr
default_md      = sha256

[ policy_any ]
countryName            = optional
stateOrProvinceName    = optional
organizationName       = optional
organizationalUnitName = optional
commonName             = supplied
EOF

intermediate_req_config_file=${config_dir}/intermediate_ca/intermediate_req.config
cat > ${intermediate_req_config_file} << EOF
[ req ]
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
countryName = US
commonName  = Springtail Test Intermediate CA, springtail.io
C = US
ST = CA
L = San Francisco
O = Springtail Inc.
EOF

intermediate_config_file=${config_dir}/intermediate_ca/intermediate.config
cat > ${intermediate_config_file} << EOF
[ ca ]
default_ca      = CA_default

[ CA_default]
dir             = ${config_dir}/intermediate_ca/  # helper variable pointing to ca specific files
database        = \$dir/index     # database of certs generated by the ca
new_certs_dir   = \$dir/new_certs/             # one dir up to make the demo easier
certificate     = \$dir/intermediate.pem     # one dir up to make the demo easier
serial          = \$dir/serial    # file with incrementing hex serial number for certs
private_key     = \$dir/intermediate.key

policy          = policy_any
email_in_dn     = no                  # recommended
unique_subject  = no                  # recommended for easier certificate rollover
copy_extensions = none                # don't honor the extensions in the csr
default_md      = sha256

[ policy_any ]
countryName            = optional
stateOrProvinceName    = optional
organizationName       = optional
organizationalUnitName = optional
commonName             = supplied
EOF

# leaf client certificate request config
leaf_client_req_config_file=${config_dir}/leaf/leaf_client_req.config
cat > ${leaf_client_req_config_file} << EOF
[ req ]
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
countryName = US
commonName  = Springtail Test Leaf Client, springtail.io
C = US
ST = CA
L = San Francisco
O = Springtail Inc.
EOF

# leaf server certificate request config
leaf_server_req_config_file=${config_dir}/leaf/leaf_server_req.config
cat > ${leaf_server_req_config_file} << EOF
[ req ]
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
countryName = US
commonName  = Springtail Test Leaf Server, springtail.io
C = US
ST = CA
L = San Francisco
O = Springtail Inc.
EOF

touch ${config_dir}/root_ca/index
cat > ${config_dir}/root_ca/serial << EOF
00
EOF

touch ${config_dir}/intermediate_ca/index
cat > ${config_dir}/intermediate_ca/serial << EOF
00
EOF

# generate root CA key and self-signed certificate
root_key_file=${config_dir}/root_ca/root.key
root_cert_request_file=${config_dir}/root_ca/requests/root.csr
root_cert_file=${config_dir}/root_ca/root.pem
openssl genrsa -out ${root_key_file} 4096
openssl req -new -key ${root_key_file} -out ${root_cert_request_file} -config ${root_req_config_file}
openssl ca -in ${root_cert_request_file} -out ${root_cert_file} -config ${root_config_file} -selfsign -extfile ${config_dir}/ca.ext -days 1095 -key ${root_key_file} -batch
ln -s ${root_cert_file} ${config_dir}/root_ca/$(openssl x509 -noout -hash -in ${root_cert_file}).0

# generate intermediate CA key and certificate
intermediate_key_file=${config_dir}/intermediate_ca/intermediate.key
intermediate_cert_request_file=${config_dir}/root_ca/requests/intermediate.csr
intermediate_cert_file=${config_dir}/intermediate_ca/intermediate.pem
openssl genrsa -out ${intermediate_key_file} 4096
openssl req -new -key ${intermediate_key_file} -out ${intermediate_cert_request_file} -config ${intermediate_req_config_file}
openssl ca -in ${intermediate_cert_request_file} -out ${intermediate_cert_file} -config ${root_config_file} -extfile ${config_dir}/ca.ext -days 730 -batch

# generate leaf client certificate
client_id='00'
leaf_client_key_file=${config_dir}/leaf/leaf_client_${client_id}.key
leaf_client_cert_request_file=${config_dir}/intermediate_ca/requests/leaf_client_${client_id}.csr
leaf_client_cert_file=${config_dir}/leaf/leaf_client_${client_id}.pem
leaf_client_intermediate_cert_file=${config_dir}/leaf/leaf_client_${client_id}_intermediate.pem
openssl genrsa -out ${leaf_client_key_file} 4096
openssl req -new -key ${leaf_client_key_file} -out ${leaf_client_cert_request_file} -config ${leaf_client_req_config_file}
openssl ca -in ${leaf_client_cert_request_file} -out ${leaf_client_cert_file} -config ${intermediate_config_file} -days 365 -batch
cat ${leaf_client_cert_file} ${intermediate_cert_file} > ${leaf_client_intermediate_cert_file}

# genereate leaf server certificate
server_id='00'
leaf_server_key_file=${config_dir}/leaf/leaf_server_${server_id}.key
leaf_server_cert_request_file=${config_dir}/intermediate_ca/requests/leaf_server_${server_id}.csr
leaf_server_cert_file=${config_dir}/leaf/leaf_server_${server_id}.pem
leaf_server_intermediate_cert_file=${config_dir}/leaf/leaf_server_${server_id}_intermediate.pem
openssl genrsa -out ${leaf_server_key_file} 4096
openssl req -new -key ${leaf_server_key_file} -out ${leaf_server_cert_request_file} -config ${leaf_server_req_config_file}
openssl ca -in ${leaf_server_cert_request_file} -out ${leaf_server_cert_file} -config ${intermediate_config_file} -days 365 -batch
cat ${leaf_server_cert_file} ${intermediate_cert_file} > ${leaf_server_intermediate_cert_file}


