#pragma once

#include <vector>
#include <functional>
#include <filesystem>
#include <future>
#include <memory>
#include <cerrno>

namespace springtail {

    /** IO Status set in response; important keep success == 0 */
    enum IOStatus {SUCCESS=0, ERROR, ERR_SEEK, ERR_NOENT, ERR_BADFD, ERR_ACCESS, ERR_ARGS, ERR_DECODE};

    // helper types for callbacks; to improve readability
    class IOResponseWrite;
    class IOResponseAppend;
    class IOResponseRead;
    class IOResponse;
    
    /** Read callback typedef */
    typedef std::function<void(std::shared_ptr<IOResponseRead> response)> io_read_callback_fn;
    /** Write callback typedef */
    typedef std::function<void(std::shared_ptr<IOResponseWrite> response)> io_write_callback_fn;
    /** Append callback typedef */
    typedef std::function<void(std::shared_ptr<IOResponseAppend> response)> io_append_callback_fn;
    /** Generic status callback typedef */
    typedef std::function<void(std::shared_ptr<IOResponse> response)> io_status_callback_fn;

    /**
     * @brief IORequest class, encapsulates an IO Request.  IORequests are generated by
     * IOHandle, and queued onto thread pool queue.
     */
    class IORequest {
    public:
        /** Type of IO request, SHUTDOWN has no data, indicates worker should shutdown */
        enum IOType { READ, APPEND, WRITE, SYNC, SHUTDOWN };

        IOType                type;         //!< type of IO
        std::filesystem::path path;         //!< underlying filename
        bool                  compressed;   //!< whether file is compressable or not

        /**
         * @brief Construct a new IORequest object
         * 
         * @param type IO type
         * @param path file name
         * @param is_compressed whether file is compressable or not
         */
        IORequest(IOType type, const std::filesystem::path &path, bool is_compressed)
            : type(type), path(path), compressed(is_compressed) {}

        /**
         * @brief Construct a new IORequest object
         * 
         * @param type IO type (optional, default is SHUTDOWN type)
         */
        IORequest(IOType type=IOType::SHUTDOWN) : type (type) {}

        virtual ~IORequest() = default;
    };

    /**
     * @brief IOResponse class, encapsulates a response to an IO request.
     */
    class IOResponse {
    public:
        IORequest::IOType     type;    //!< IO type
        std::filesystem::path path;    //!< underlying filename
        IOStatus              status;  //!< status of request

        /**
         * @brief Construct a new IOResponse object
         * 
         * @param type   type of IO
         * @param path   underlying file path
         * @param status status (default=SUCCESS)
         */
        IOResponse(IORequest::IOType type, const std::filesystem::path &path, 
                   IOStatus status=IOStatus::SUCCESS)
            : type(type), path(path), status(status) {}

        /**
         * @brief Set the status object
         * 
         * @param iostatus new status
         */
        inline void set_status(IOStatus iostatus) { status = iostatus; }

        /**
         * @brief Set the status object based on errno.
         * 
         * @param fh_errno errno as reported by system call
         */
        inline void set_status(int fh_errno) 
        {
            if (fh_errno == -1) { return; }
            switch (fh_errno) {  // XXX need to add additional mappings
                case 0:
                    status = IOStatus::SUCCESS;
                    break;
                default:
                    status = IOStatus::ERROR;
            }
        }

        /**
         * @brief Is status success
         * 
         * @return true   if success
         * @return false  if failure
         */
        inline bool is_success() { return status == IOStatus::SUCCESS; }
    };


    /**
     * @brief Write response
     */
    class IOResponseWrite : public IOResponse {
    public: 
        /** offset of this write */
        uint64_t offset;

        /** next offset after this write (length of write data + hdr) */
        uint64_t next_offset;

        IOResponseWrite(std::filesystem::path &path, uint64_t offset, uint64_t next_offset, IOStatus status=IOStatus::SUCCESS)
            : IOResponse(IORequest::IOType::WRITE, path, status), offset(offset), next_offset(next_offset) {}

        IOResponseWrite(std::filesystem::path &path, IOStatus status=IOStatus::ERROR)
            : IOResponse(IORequest::IOType::WRITE, path, status) {}
    };

    /**
     * @brief Write request
     */
    class IORequestWrite : public IORequest {
    public:
        uint64_t                                        offset;   //!< offset of this write
        std::vector<std::shared_ptr<std::vector<char>>> data;     //!< data vectors
        std::promise<std::shared_ptr<IOResponseWrite>>  promise;  //!< promise for async completion
        io_write_callback_fn                            callback; //!< callback (optional)

        IORequestWrite(std::filesystem::path &path, bool is_compressed, 
                       uint64_t offset, std::shared_ptr<std::vector<char>> datavec, 
                       io_write_callback_fn cb) 
            : IORequest(IORequest::IOType::WRITE, path, is_compressed),
              offset(offset), callback(cb) { data.push_back(datavec); }

        IORequestWrite(std::filesystem::path &path, bool is_compressed, 
                uint64_t offset, std::shared_ptr<std::vector<char>> datavec) 
            : IORequest(IORequest::IOType::WRITE, path, is_compressed),
              offset(offset) { data.push_back(datavec); }

        IORequestWrite(std::filesystem::path &path, bool is_compressed, uint64_t offset, 
                       const std::vector<std::shared_ptr<std::vector<char>>> &data, 
                       io_write_callback_fn cb) 
            : IORequest(IORequest::IOType::WRITE, path, is_compressed),
              offset(offset), data(data), callback(cb) {}

        IORequestWrite(std::filesystem::path &path, bool is_compressed, uint64_t offset, 
                       const std::vector<std::shared_ptr<std::vector<char>>> &data) 
            : IORequest(IORequest::IOType::WRITE, path, is_compressed),
              offset(offset), data(data) {}

        /**
         * @brief Complete the request, issue the callback if exists, set the value of the promise
         * 
         * @param res       Ptr to result response
         * @param fh_errno  system call errno (or -1 if no error)
         */
        inline void complete(std::shared_ptr<IOResponseWrite> res, int fh_errno=-1)
        {
            res->set_status(fh_errno);
            promise.set_value(res);
            if (callback) {
                callback(res);
            }
        }
    };

    /**
     * @brief Append response
     */
    class IOResponseAppend : public IOResponse {
    public:
        /** offset of the append */
        uint64_t offset;

        /** next offset -- also EOF marker */
        uint64_t next_offset;

        IOResponseAppend(std::filesystem::path &path, uint64_t offset, uint64_t next_offset, IOStatus status=IOStatus::SUCCESS)
            : IOResponse(IORequest::IOType::APPEND, path, status), offset(offset), next_offset(next_offset) {}

        IOResponseAppend(std::filesystem::path &path, IOStatus status=IOStatus::ERROR)
            : IOResponse(IORequest::IOType::APPEND, path, status) {}
    };

    /**
     * @brief Append request
     */
    class IORequestAppend : public IORequest {
    public:
        std::vector<std::shared_ptr<std::vector<char>>> data;     //!< data vectors
        std::promise<std::shared_ptr<IOResponseAppend>> promise;  //!< promise for async completion
        io_append_callback_fn callback;                           //!< callback (optional)

        IORequestAppend(std::filesystem::path &path, bool is_compressed, 
                        std::shared_ptr<std::vector<char>> datavec, 
                        io_append_callback_fn cb) 
            : IORequest(IORequest::IOType::APPEND, path, is_compressed),
              callback(cb) { data.push_back(datavec); }

        IORequestAppend(std::filesystem::path &path, bool is_compressed, 
                        std::shared_ptr<std::vector<char>> datavec) 
            : IORequest(IORequest::IOType::APPEND, path, is_compressed)
        { data.push_back(datavec); }

        IORequestAppend(std::filesystem::path &path, bool is_compressed, 
                       const std::vector<std::shared_ptr<std::vector<char>>> &data, 
                       io_append_callback_fn cb) 
            : IORequest(IORequest::IOType::APPEND, path, is_compressed),
              data(data), callback(cb) {}

        IORequestAppend(std::filesystem::path &path, bool is_compressed,
                        const std::vector<std::shared_ptr<std::vector<char>>> &data) 
            : IORequest(IORequest::IOType::APPEND, path, is_compressed), data(data) {}

        /**
         * @brief Complete the request, issue the callback if exists, set the value of the promise
         * 
         * @param res       Ptr to result response
         * @param fh_errno  system call errno (or -1 if no error)
         */
        inline void complete(std::shared_ptr<IOResponseAppend> res, int fh_errno=-1) 
        {
            res->set_status(fh_errno);
            promise.set_value(res);
            if (callback) {
                callback(res);
            }
        }
    };

    /**
     * @brief Read response
     */
    class IOResponseRead : public IOResponse {
    public:
        /** current offset for read */
        uint64_t offset;
        
        /** next valid offset after this read */
        uint64_t next_offset;

        /** Data response vector */
        std::vector<std::shared_ptr<std::vector<char>>> data;

        IOResponseRead(std::filesystem::path &path, IOStatus status, uint64_t offset,
                       std::vector<std::shared_ptr<std::vector<char>>> &data)
            : IOResponse(IORequest::IOType::READ, path, status),
              offset(offset), data(data) {}

        IOResponseRead(std::filesystem::path &path, IOStatus status=IOStatus::ERROR)
            : IOResponse(IORequest::IOType::READ, path, status) {}
    };

    /**
     * @brief Read request
     */
    class IORequestRead : public IORequest {
    public:
        uint64_t offset;                                        //!< offset of this read
        std::promise<std::shared_ptr<IOResponseRead>> promise;  //!< promise for async completion
        io_read_callback_fn callback;                           //!< callback (optional)

        IORequestRead(std::filesystem::path &path, bool is_compressed, 
                      uint64_t offset, io_read_callback_fn cb)
            : IORequest(IORequest::IOType::READ, path, is_compressed),
              offset(offset), callback(cb) {}

        IORequestRead(std::filesystem::path &path, bool is_compressed, 
                      uint64_t offset)
            : IORequest(IORequest::IOType::READ, path, is_compressed), offset(offset) {}

        /**
         * @brief Complete the request, issue the callback if exists, set the value of the promise
         * 
         * @param res       Ptr to result response
         * @param fh_errno  system call errno (or -1 if no error)
         */
        inline void complete(std::shared_ptr<IOResponseRead> res, int fh_errno=-1) 
        {
            res->set_status(fh_errno);
            promise.set_value(res);
            if (callback) {
                callback(res);
            }
        }
    };

    /**
     * @brief Sync request
     */
    class IORequestSync : public IORequest {
    public:
        std::promise<std::shared_ptr<IOResponse>> promise;  //!< promise for async completion
        io_status_callback_fn callback;                     //!< status callback (optional)

        IORequestSync(std::filesystem::path &path, bool is_compressed, 
                      io_status_callback_fn cb)
            : IORequest(IORequest::IOType::SYNC, path, is_compressed),
              callback(cb) {}

        IORequestSync(std::filesystem::path &path, bool is_compressed)
            : IORequest(IORequest::IOType::SYNC, path, is_compressed) {}

        /**
         * @brief Complete the request, issue the callback if exists, set the value of the promise
         * 
         * @param res       Ptr to result response
         * @param fh_errno  system call errno (or -1 if no error)
         */
        inline void complete(std::shared_ptr<IOResponse> res, int fh_errno=-1) 
        {
            res->set_status(fh_errno);
            promise.set_value(res);
            if (callback) {
                callback(res);
            }
        }
    };
}