#pragma once

#include <vector>
#include <functional>
#include <filesystem>
#include <future>
#include <memory>
#include <iostream>
#include <cerrno>

#include <storage/compressors.hh>

namespace springtail {

    /** IO Status set in response; important keep success == 0 */
    enum IOStatus { SUCCESS=0, ERROR, 
                    ERR_NOENT, ERR_ACCESS, ERR_ARGS,
                    ERR_NOSPC, ERR_BADFD, ERR_DECODE, ERR_CKSUM };

    // forward definitions of response types for callbacks; to improve readability
    class IOResponseWrite;
    class IOResponseAppend;
    class IOResponseRead;
    class IOResponse;
    
    class IOSysFH;

    /** Read callback typedef */
    typedef std::function<void(std::shared_ptr<IOResponseRead> response)> io_read_callback_fn;
    /** Write callback typedef */
    typedef std::function<void(std::shared_ptr<IOResponseWrite> response)> io_write_callback_fn;
    /** Append callback typedef */
    typedef std::function<void(std::shared_ptr<IOResponseAppend> response)> io_append_callback_fn;
    /** Generic status callback typedef */
    typedef std::function<void(std::shared_ptr<IOResponse> response)> io_status_callback_fn;

    /**
     * @brief IORequest class, encapsulates an IO Request.  IORequests are generated by
     * IOHandle, and queued onto thread pool queue.
     */
    class IORequest {
    public:
        /** Type of IO request, SHUTDOWN has no data, indicates worker should shutdown */
        enum IOType { READ, APPEND, WRITE, SYNC, SHUTDOWN };

        IOType                type;         ///< type of IO
        std::filesystem::path path;         ///< underlying filename
        bool                  compressed;   ///< whether file is compressable or not

        /**
         * @brief Construct a new IORequest object
         * @param type IO type
         * @param path file name
         * @param is_compressed whether file is compressable or not
         */
        IORequest(IOType type, const std::filesystem::path &path, bool is_compressed)
            : type(type), path(path), compressed(is_compressed) {}

        /**
         * @brief Construct a new IORequest object
         * @param type IO type (optional, default is SHUTDOWN type)
         */
        IORequest(IOType type=IOType::SHUTDOWN) : type (type) {}

        /** virtual destructor for clean inheritence destruction */
        virtual ~IORequest() = default;

        /**
         * @brief Get the type as a string
         * @return std::string 
         */
        std::string get_type();

        /**
         * @brief Overload () for execution from worker thread.
         *        Main entry from worker thread
         */
        void operator()() {
            _process_request();
        }

    private:
        /**
         * @brief Entry from worker thread for processing io request
         */
        void _process_request();

        /**
         * @brief Worker thread internal issue_request call
         * @param request IORequest to process
         * @param fh      File handle for request
         */
        void _issue_request(std::shared_ptr<IOSysFH> fh,
                            std::shared_ptr<Compressor> compressor,
                            std::shared_ptr<Decompressor> decompressor);

        /**
         * @brief Handle caught exception
         * @param request IORequest ptr
         * @param exc     Exception caught
         */
        void _handle_error(const std::exception &exc);
    };

    /**
     * @brief IOResponse class, encapsulates a response to an IO request.
     */
    class IOResponse {
    public:
        IORequest::IOType     type;    ///< IO type
        std::filesystem::path path;    ///< underlying filename
        IOStatus              status;  ///< status of request

        /**
         * @brief Construct a new IOResponse object
         * @param request ptr to IORequest object; extract type and path from it
         * @param status status (default=IOStatus::Error)
         */
        IOResponse(IORequest *request, IOStatus status=IOStatus::ERROR)
            : type(request->type), path(request->path), status(status)//, request(request)
        {}

        /**
         * @brief Set the status object
         * @param iostatus new status
         */
        inline void set_status(IOStatus iostatus) { status = iostatus; }

        /**
         * @brief Set the status object based on errno.
         * @param fh_errno errno as reported by system call
         */
        inline void set_status(int fh_errno) 
        {
            if (fh_errno == -1) { return; }
            switch (fh_errno) {
                case 0:
                    status = IOStatus::SUCCESS;
                    break;
                case EBADF:  // invalid file descriptor
                    status = IOStatus::ERR_BADFD;
                    break;
                case EINVAL: // invalid arguments
                    status = IOStatus::ERR_ARGS;
                    break;
                case EPERM:  // no permission
                    status = IOStatus::ERR_ACCESS;
                    break;
                case ENOSPC: // ran out of space
                    status = IOStatus::ERR_NOSPC;
                    break;
                case ENOENT: // no file exists
                    status = IOStatus::ERR_NOENT;
                    break;
                default:
                    status = IOStatus::ERROR;
            }
        }

        /**
         * @brief Is status success
         * @return true   if success
         * @return false  if failure
         */
        inline bool is_success() { return status == IOStatus::SUCCESS; }
    };

    /**
     * @brief Template to help store the promise and callback and handle the response completion;
     *        Inherits from IORequest
     * @tparam T IOResponse type
     */
    template <typename ResponseClass>
    class IORequestTemplate : public IORequest {
    public:
        std::promise<std::shared_ptr<ResponseClass>> promise;  ///< promise for async completion
        std::function<void(std::shared_ptr<ResponseClass> response)> callback; ///< callback (optional)

        IORequestTemplate(IOType type, const std::filesystem::path &path, bool is_compressed,
                          std::function<void(std::shared_ptr<ResponseClass> response)> callback)
            : IORequest(type, path, is_compressed), callback(callback) {}

        /**
         * @brief Complete the request, issue the callback if exists, set the value of the promise
         * @param res       Ptr to result response
         * @param fh_errno  system call errno (or -1 if no error)
         */
        void complete(std::shared_ptr<ResponseClass> res, int fh_errno=-1) {
            res->set_status(fh_errno);
            promise.set_value(res);
            if (callback) {
                callback(res);
            }
        }

        /**
         * @brief Complete the request, issue the callback if exists, set value of the promise
         * @param res      Ptr to result response
         * @param status   IOStatus status
         */
        void complete(std::shared_ptr<ResponseClass> res, IOStatus status) {
            res->set_status(status); 
            promise.set_value(res);
            if (callback) {
                callback(res);
            }
        }
    };

    /**
     * @brief Write request
     */
    class IORequestWrite : public IORequestTemplate<IOResponseWrite> {
    public:
        /** offset of this write */
        uint64_t                                        offset;

        /** data vectors */
        std::vector<std::shared_ptr<std::vector<char>>> data;

        IORequestWrite(std::filesystem::path &path, bool is_compressed, 
                       uint64_t offset, std::shared_ptr<std::vector<char>> datavec, 
                       io_write_callback_fn cb) 
            : IORequestTemplate(IORequest::IOType::WRITE, path, is_compressed, cb),
              offset(offset) { data.push_back(datavec); }

        IORequestWrite(std::filesystem::path &path, bool is_compressed, uint64_t offset, 
                       const std::vector<std::shared_ptr<std::vector<char>>> &data, 
                       io_write_callback_fn cb) 
            : IORequestTemplate(IORequest::IOType::WRITE, path, is_compressed, cb),
              offset(offset), data(data) {}
    };

    /**
     * @brief Write response
     */
    class IOResponseWrite : public IOResponse {
    public: 
        /** offset of this write */
        uint64_t offset;

        /** next offset after this write (length of write data + hdr) */
        uint64_t next_offset;

        /**
         * @brief Construct a new IOResponseWrite object
         * @param request IORequestWrite to be used in callback or future
         * @param status  optional status, default=IOStatus::ERROR
         */
        IOResponseWrite(IORequestWrite *request, IOStatus status=IOStatus::ERROR)
            : IOResponse(request, status), offset(request->offset) {}
    };

    /**
     * @brief Append request
     */
    class IORequestAppend : public IORequestTemplate<IOResponseAppend> {
    public:
        /** Data vectors */
        std::vector<std::shared_ptr<std::vector<char>>> data;

        IORequestAppend(std::filesystem::path &path, bool is_compressed, 
                        std::shared_ptr<std::vector<char>> datavec, 
                        io_append_callback_fn cb) 
            : IORequestTemplate(IORequest::IOType::APPEND, path, is_compressed, cb)
              { data.push_back(datavec); }

        IORequestAppend(std::filesystem::path &path, bool is_compressed, 
                       const std::vector<std::shared_ptr<std::vector<char>>> &data, 
                       io_append_callback_fn cb) 
            : IORequestTemplate(IORequest::IOType::APPEND, path, is_compressed, cb), data(data) {}
    };

    /**
     * @brief Append response
     */
    class IOResponseAppend : public IOResponse {
    public:
        /** offset of the append */
        uint64_t offset;

        /** next offset -- also EOF marker */
        uint64_t next_offset;

        /**
         * @brief Construct a new IOResponseAppend object
         * @param request IORequestAppend to be used in callback or future
         * @param status  optional status, default=IOStatus::ERROR
         */
        IOResponseAppend(IORequestAppend *request, IOStatus status=IOStatus::ERROR)
            : IOResponse(request, status) {}
    };

    /**
     * @brief Read request
     */
    class IORequestRead : public IORequestTemplate<IOResponseRead> {
    public:
        /** offset of this read */
        uint64_t offset; 

        IORequestRead(std::filesystem::path &path, bool is_compressed, 
                      uint64_t offset, io_read_callback_fn cb)
            : IORequestTemplate(IORequest::IOType::READ, path, is_compressed, cb),
              offset(offset) {}
    };

    /**
     * @brief Read response
     */
    class IOResponseRead : public IOResponse {
    public:
        /** current offset for read */
        uint64_t offset;
        
        /** next valid offset after this read */
        uint64_t next_offset;

        /** Data response vector */
        std::vector<std::shared_ptr<std::vector<char>>> data;

        /**
         * @brief Construct a new IOResponseRead object
         * @param request IORequestRead to be used in callback or future
         * @param status  optional status, default=IOStatus::ERROR
         */
        IOResponseRead(IORequestRead *request, IOStatus status=IOStatus::ERROR)
            : IOResponse(request, status), offset(request->offset) {}
    };

    /**
     * @brief Sync request
     */
    class IORequestSync : public IORequestTemplate<IOResponse> {
    public:
        IORequestSync(std::filesystem::path &path, bool is_compressed, 
                      io_status_callback_fn cb)
            : IORequestTemplate(IORequest::IOType::SYNC, path, is_compressed, cb) {}
    };
}