test_folder: 'test_cases'
system_json_path: '../../system.json.test'
build_dir: '../../debug'
tmp_config_dir: '/tmp/tmp_springtail_config'

overlay_config:

  # uses a small repl log size to force more frequent log rotations
  small_log_rotate:
    # no parameters
    params: ~

  # uses a small repl log size to force more frequent log rotations together with streaming postgres config
  small_log_rotate_with_streaming:
    params:
      postgres_config:
        logical_decoding_work_mem: 64

  # uses a small data cache size to force more frequent eviction
  small_cache_size:
    # no parameters
    params: ~

  # uses a small worker mem size to ensure streaming mode
  streaming_postgres_config:
    params:
      postgres_config:
        logical_decoding_work_mem: 64

  # set the test config to run the test and verify steps against the proxy
  integration_test_config:
    params:
      use_proxy_for_test: true
      use_proxy_for_verify: true

  # special configuration for testing include schema
  include_schema_config:
    # no parameters
    params: ~

configs:
  # configuration for nightly builds
  nightly:
    - overlay: ~
      test_sets: 'all'
    - overlay: 'small_log_rotate'
      test_sets: [ 'recovery' ]
    - overlay: 'small_log_rotate_with_streaming'
      test_sets: [ 'recovery' ]
    - overlay: 'small_cache_size'
      test_sets: [ 'basic' ]
    - overlay: 'streaming_postgres_config'
      test_sets: [ 'recovery', 'large_data' ]
    # temporary commented out because it does not work yet
    # - overlay: 'integration_test_config'
    #   test_sets: ['basic', 'framework']
    - overlay: 'include_schema_config'
      test_sets: [ 'include_schema' ]

  # configuration for github CI, split into multiple parts to allow parallel execution
  # Long tests:
  #  - basic ~ 4min
  #  - recovery (small log rotate) ~ 5min
  #  - recovery (small log rotate with streaming) ~ 6min
  #  - small cache size ~ 4min
  #  - streaming postgres config ~ 5min
  github_ci_p1:
    - overlay: ~
      test_sets: [ 'basic', 'framework', 'preload' ]
    - overlay: 'include_schema_config'
      test_sets: [ 'include_schema' ]
    - overlay: ~
      test_sets: [ 'numeric', ]
    - overlay: 'small_cache_size'
      test_sets: [ 'basic' ]

  github_ci_p2:
    - overlay: ~
      test_sets: [ 'enum_bits', 'complex' ]
    - overlay: 'small_log_rotate'
      test_sets: [ 'recovery' ]

  github_ci_p3:
    - overlay: 'small_log_rotate_with_streaming'
      test_sets: [ 'recovery' ]
    - overlay: 'streaming_postgres_config'
      test_sets: [ 'recovery' ]

  # this configuration runs when there is nothing specified on the command line
  default:
    - overlay: ~
      test_sets: [ 'basic', 'framework', 'preload', 'enum_bits', 'complex', 'numeric', 'query_benchmark' ]
    - overlay: 'small_log_rotate'
      test_sets: [ 'recovery' ]
    - overlay: 'small_log_rotate_with_streaming'
      test_sets: [ 'recovery' ]
    - overlay: 'small_cache_size'
      test_sets: [ 'basic' ]
    - overlay: 'streaming_postgres_config'
      test_sets: [ 'recovery', 'large_data' ]
    - overlay: 'include_schema_config'
      test_sets: [ 'include_schema' ]
    
