# Folder holding the test cases
test_folder: 'test_cases'

# the location of the Springtail configuration file to use
system_json_path: '../../system.json.test'

# the location of the Springtail build
build_dir: '../../debug'

# the default test sets to run
default_test_sets: ['preload']

# the configuration overlays to apply
overlays:
  # uses a small repl log size to force more frequent log rotations
  small_log_rotate:
    test_sets: ['recovery']
  # uses a small data cache size to force more frequent eviction
  small_cache_size:
    test_sets: ['basic']
  # uses a small worker mem size to ensure streaming mode
  streaming_postgres_config:
    test_sets: ['basic']
    params:
      postgres_config:
        logical_decoding_work_mem: 64
  # set the test config to run the test and verify steps against the proxy
  integration_test_config:
    test_sets: ['basic', 'framework', 'recovery']
    params:
      use_proxy_for_test: true
      use_proxy_for_verify: true
