- name: Install core packages
  ansible.builtin.apt:
    name:
      - autoconf
      - binutils-dev
      - bison
      - build-essential
      - ca-certificates
      - clang-format
      - cmake
      - curl
      - flex
      - g++-14
      - gcc-14
      - gdb
      - git
      - gnupg
      - gpg
      - iproute2
      - jq
      - libbsd-dev
      - libdw-dev
      - libdwarf-dev
      - libelf-dev
      - linux-libc-dev
      - lsb-release
      - net-tools
      - ninja-build
      - nmap
      - openssh-server
      - pkg-config
      - postgresql-16
      - postgresql-contrib-16
      - procps
      - python3
      - python3-boto3
      - python3-jinja2
      - python3-lxml
      - python3-pip
      - python3-psutil
      - python3-psycopg2
      - python3-redis
      - python3-requests
      - python3-yaml
      - redis-server
      - software-properties-common
      - rsync
      - sudo
      - tar
      - unzip
      - wget
      - zip

    update_cache: true
    state: present
    autoclean: true

- name: Install additional packages
  ansible.builtin.apt:
    name:
      - dnsutils
      - emacs-nox
      - htop
      - iftop
      - iputils-ping
      - netcat-openbsd
      - traceroute
      - vim
    state: present
    update_cache: true
  when: install_additional_packages

- name: Set timezone non-interactively
  ansible.builtin.apt:
    name: tzdata
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Allow ptrace by lowering kernel.yama.ptrace_scope
  ansible.builtin.replace:
    path: /etc/sysctl.d/10-ptrace.conf
    regexp: '^kernel.yama.ptrace_scope\s*=\s*1'
    replace: 'kernel.yama.ptrace_scope = 0'

- name: Install AWS CLI v2
  ansible.builtin.shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "/tmp/awscliv2.zip"
    unzip -q /tmp/awscliv2.zip -d /tmp
    /tmp/aws/install --update
    rm -f /tmp/awscliv2.zip