name: Build Coordinator

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'The type of build to perform. For release build, we upload to the "prod-data-share.springtail.internal" bucket (in production account), for debug builds we upload to the "data-share.springtail.internal" bucket (in development account).'
        type: choice
        default: "release"
        options:
          - release
          - debug

permissions:
  id-token: write
  contents: read
  checks: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    timeout-minutes: 35
    container:
      image: ghcr.io/springtail-inc/${{ inputs.build_type == 'release'  && vars.RELEASE_BUILDER_IMAGE_VERSION  || vars.BUILDER_IMAGE_VERSION }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          git config --global --add safe.directory /__w/springtail/springtail
          if [ "${{ inputs.build_type }}" = "release" ]; then
            ./release.sh
          else
            ./debug.sh
          fi

      - name: Pack Coordinator
        run: |
          cp -R python stc
          rm -rf stc/benchmarks stc/testing
          # Overwrite the stc/coordinator/config.yaml file with the following content
          echo "install_dir: '/opt/springtail'" > stc/coordinator/config.yaml
          echo "production: True" >> stc/coordinator/config.yaml
          echo "log_rotation_size: 104857600" >> stc/coordinator/config.yaml
          echo "log_rotation_count: 10" >> stc/coordinator/config.yaml
          tar -czf stc.tar.gz stc

      - name: Upload Coordinator Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Coordinator Package'
          path: stc.tar.gz
