name: PR Comment Actions (PR to Main)

on:
  issue_comment:
    types: [ created ]
  # By default, this workflow will be triggered when PR is first opened
  #You can also invoke this manually.
  workflow_dispatch:


permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  test:
    if: |
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '/tests')
    uses: ./.github/workflows/test.yml
    with:
      builder_image_version_tag: ${{ vars.DEV_SUPPORT_ECR_REPO_URI }}:${{ vars.BUILDER_IMAGE_VERSION }}
      num_procs: "${{ vars.NUM_PROCS }}"
      ref: ${{ github.event.issue.pull_request.head.ref }}
    secrets:
      aws_role_arn: "${{ secrets.DEV_AWS_ROLE_ARN }}"
      aws_ecr_docker_password: "${{ secrets.DEV_SUPPORT_ECR_PW }}"
