# This is an automatically triggered workflow that runs every 8 hours to
# refresh the ECR login credential. This is necessary because we are using a base builder image in ECRon:
# to launch the GitHub Action container for tests and build.
# The ECR login credential is valid for 12 hours by default
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  update-ecr-pw:
    runs-on: ubuntu-latest
    env:
      # need an Github Access token with Admin access to update secret
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::891377357651:role/GitHubOIDCStack-GHDeploymentRolespringtail4901D08A-77JHxuAaXoIY
          role-session-name: tempSession
          aws-region: us-east-1
      - name: Get ECR password and update secret
        run: |
          ECR_PW=$(aws ecr get-login-password --region us-east-1 --output text)
          gh secret set ECR_PW --body "$ECR_PW"
