name: Nightly Build & Test
on:
  schedule:
    # Runs at 07:00 UTC, which corresponds to 11:00 PM PT
    - cron: '0 7 * * *'
  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/rw-build-container.yml
    with:
      base_image_tag: ${{ vars.IMAGE_TAG_DEBUG }}
      build_type: "debug"
    secrets:
      aws_role_arn: "${{ secrets.DEV_AWS_ROLE_ARN }}"
      aws_ecr_docker_password: "${{ secrets.DEV_SUPPORT_ECR_PW }}"

  build-with-time-traces:
    uses: ./.github/workflows/rw-build-container.yml
    with:
      base_image_tag: ${{ vars.IMAGE_TAG_DEBUG }}
      build_type: "release"
      springtail_include_time_traces: true
    secrets:
      aws_role_arn: "${{ secrets.DEV_AWS_ROLE_ARN }}"
      aws_ecr_docker_password: "${{ secrets.DEV_SUPPORT_ECR_PW }}"

  unit-test:
    uses: ./.github/workflows/rw-run-unit-test.yml
    needs: [ build ]
    with:
      image_tag: ${{ needs.build.outputs.output_image_tag }}
    secrets:
      aws_role_arn: "${{ secrets.DEV_AWS_ROLE_ARN }}"
      aws_ecr_docker_password: "${{ secrets.DEV_SUPPORT_ECR_PW }}"

  multi-rounds-integration-test:
    uses: ./.github/workflows/rw-run-integration-test.yml
    needs: [ build ]
    with:
      image_tag: ${{ needs.build.outputs.output_image_tag }}
      config_to_run: "nightly"
      system_settings_override: '.github/workflows/nightly.overrides.json'
      iterations: '2'
    secrets:
      aws_role_arn: "${{ secrets.DEV_AWS_ROLE_ARN }}"
      aws_ecr_docker_password: "${{ secrets.DEV_SUPPORT_ECR_PW }}"

  performance-test:
    uses: ./.github/workflows/rw-run-performance-test.yml
    needs: [ build-with-time-traces ]
    with:
      image_tag: ${{ needs.build-with-time-traces.outputs.output_image_tag }}
      system_settings_override: '.github/workflows/nightly.overrides.json'
    secrets:
      aws_role_arn: "${{ secrets.DEV_AWS_ROLE_ARN }}"
      aws_ecr_docker_password: "${{ secrets.DEV_SUPPORT_ECR_PW }}"