name: PR Actions (PR to Main)

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
  workflow_dispatch:


permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      builder_image_version_tag: ${{ vars.DEV_SUPPORT_ECR_REPO_URI }}:${{ vars.BUILDER_IMAGE_VERSION }}
      num_procs: "${{ vars.NUM_PROCS }}"
    secrets:
      aws_role_arn: "${{ secrets.DEV_AWS_ROLE_ARN }}"
      aws_ecr_docker_password: "${{ secrets.DEV_SUPPORT_ECR_PW }}"
