name: Run Performance Test

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'The image version tag for the base builder to pull.'
        type: string
        required: true
      system_settings_override:
        description: 'A JSON file that contains overrides for the system.json.settings file.'
        type: string
        required: false
        default: '.github/workflows/ci-general.overrides.json'
    secrets:
      aws_role_arn:
        description: "The ARN of the role to assume."
        required: true
      aws_ecr_docker_password:
        description: "The password for the ECR docker registry."
        required: true
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  checks: write


jobs:
  nightly_job:
    name: Nightly Job
    runs-on: warp-ubuntu-latest-arm64-4x
    timeout-minutes: 180
    container:
      image: ${{ vars.DEV_SUPPORT_ECR_REPO_URI }}:${{ vars.BUILDER_IMAGE_VERSION }}
      credentials:
        username: AWS
        password: ${{ secrets.DEV_SUPPORT_ECR_PW }}

    # You can use this environment variable to access the current working directory
    env:
      S3_BUCKET_NAME: devsupport.springtail.internal
      VCPKG_FORCE_SYSTEM_BINARIES: 1
      VCPKG_ROOT: /home/dev/external/vcpkg
      DOCKER: 1
      ZIC: true
      USER: root
      PYTHONUNBUFFERED: 1
      CWD: ${{ github.workspace }}
      DATA_SHARE_BUCKET_NAME: data-share.springtail.internal
      DEVSUPPORT_BUCKET_NAME: devsupport.springtail.internal
      PACKAGES_S3_PREFIX: nightly-builds
      TEST_LOGS_S3_PREFIX: nightly-testlogs
      NUM_PROCS: ${{ vars.NUM_PROCS }}
      #INTEGRATION_TEST_ITERATIONS: ${{ vars.INTEGRATION_TEST_ITERATIONS || 1 }}
      INTEGRATION_TEST_ITERATIONS: 3
      # The path to the Springtail logs, keep consistent with the `log_path` inside
      # system.json.test
      SPRINGTAIL_LOG_PATH: /opt/springtail/logs

    steps:
      - name: Prepare Tests
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          # Override some settings in the config file
          .github/workflows/scripts/merge_system_settings.py system.json.settings ${SYSTEM_SETTINGS_OVERRIDE} system.json.test

          mkdir -p /opt/springtail/pids
          service redis-server start

          # Copy over the fdw_config file to the designated location
          conf_file=/etc/postgresql/16/main/postgresql.conf
          fdw_config_file_path=$(grep -E "^springtail_fdw.config_file_path" $conf_file | awk '{print $3}' | tr -d "'")
          mkdir -p $(dirname $fdw_config_file_path)
          cp system.json.test $fdw_config_file_path

      - name: Run performance test
        run: |
          cd python/testing
          python3 springtail.py -f ../../system.json.test --load-redis --build-dir ../../debug

          cd ../performance

          _LOG_FLAG="failed"
          # Run performance tests
          python3 performance_runner.py -c performance_config.yaml 2>&1 | tee tmplog

          # Grab the success/failure status of the performance tests
          if [ $? -eq 0 ] 
          then 
            _LOG_FLAG="succeeded"
          fi

          # Upload performance test logs
          _TIMESTAMP=$(date +%s)
          log_file="performance-test-${GITHUB_SHORT_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.log" 
          log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${log_file}"
          aws s3 cp tmplog $log_s3_key
          echo "*** Performance Test Log S3 Key: $log_s3_key"
          rm -f tmplog

          # Go back to the testing folder to use the springtail.py to dump the logs
          cd ../testing

          # Springtail service logs
          springtail_log_file="springtail-performance-${GITHUB_SHORT_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.tar.gz"
          output=$(python3 springtail.py --dump -f ../../system.json.test -b ../../debug)
          log_dump_file_name=$(echo $output | cut -f2 -d':' | xargs | head -1)
          springtail_log_s3_key="${TEST_LOG_S3_FULL_PREFIX}/${springtail_log_file}"
          aws s3 cp $log_dump_file_name $springtail_log_s3_key
          echo "*** Springtail Log S3 Key: $springtail_log_s3_key"
          rm -f $log_dump_file_name

          if [ "$_LOG_FLAG" = "failed" ]; then
            echo "*** Performance test failed"
            exit 1
          fi
          echo "*** Finished running performance tests"
