name: Run Performance Test

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'The image version tag for the base builder to pull.'
        type: string
        required: true
      system_settings_override:
        description: 'A JSON file that contains overrides for the system.json.settings file.'
        type: string
        required: false
        default: '.github/workflows/ci-general.overrides.json'
      s3_log_prefix:
        description: 'The S3 prefix for logs. This is the folder inside the S3 bucket where logs will be stored.'
        type: string
        required: true
      build_type:
        description: 'The type of build to base the tests on. "release" or "debug". The type of build need to match the base image type.'
        type: string
        required: true
        default: "debug"
      timeout_minutes:
        description: 'The timeout in minutes for the entire job.'
        type: number
        required: false
        default: 30
      reuse_code:
        description: 'Whether to reuse the existing code from /home/dev/springtail or do a fresh checkout.'
        type: boolean
        required: false
      num_procs:
        description: 'The number of parallel processes to use for rebuilding. Only used if reuse_code is false.'
        type: string
        required: false
        default: "4"
    secrets:
      aws_role_arn:
        description: "The ARN of the role to assume."
        required: true
      aws_ecr_docker_password:
        description: "The password for the ECR docker registry."
        required: true
    outputs:
      test_log_s3_uri:
        description: "The full S3 prefix where the test logs are stored."
        value: ${{ jobs.test.outputs.test_log_s3_uri }}
      springtail_log_s3_uri:
        description: "The full S3 prefix where the springtail service logs are stored."
        value: ${{ jobs.test.outputs.springtail_log_s3_uri }}
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  checks: write


jobs:
  test:
    name: performance-test
    runs-on: warp-ubuntu-latest-arm64-4x
    timeout-minutes: ${{ inputs.timeout_minutes }}
    container:
      image: ${{ vars.DEV_SUPPORT_ECR_REPO_URI }}:${{ inputs.image_tag }}
      credentials:
        username: AWS
        password: ${{ secrets.aws_ecr_docker_password }}
      options: >-
        --init
        -v /var/run/docker.sock:/var/run/docker.sock
    outputs:
      test_log_s3_uri: ${{ steps.run-test.outputs.test_log_s3_uri }}
      springtail_log_s3_uri: ${{ steps.run-test.outputs.springtail_log_s3_uri }}
    env:
      CI_WORKSPACE: /__w/springtail/springtail
      CI_BUILD_TYPE: ${{ inputs.build_type }}
      S3_LOGS_PREFIX_FULL: "s3://devsupport.springtail.internal/${{ inputs.s3_log_prefix }}"
      ECR_REPO_URI: ${{ vars.DEV_SUPPORT_ECR_REPO_URI }}
      IMAGE_TAG: ${{ inputs.image_tag }}
      SYSTEM_SETTINGS_OVERRIDE: ${{ inputs.system_settings_override }}
      VCPKG_FORCE_SYSTEM_BINARIES: 1
      VCPKG_ROOT: /home/dev/external/vcpkg
      DOCKER: 1
      ZIC: true
      USER: root
      PYTHONUNBUFFERED: 1
      GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_LATEST_SHA: ${{ github.event.pull_request.head.sha }}
      NUM_PROCS: ${{ inputs.num_procs }}
      INTEGRATION_TEST_CONFIG: ${{ inputs.config_to_run }}
      INTEGRATION_TEST_ITERATIONS: ${{ inputs.iterations }}
      SPRINGTAIL_LOG_PATH: /var/log/springtail.log

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: inputs.reuse_code == false
        with:
          clean: true

      - name: Reuse existing code
        if: inputs.reuse_code == true
        run: |
          echo "Reusing existing code from /home/dev/springtail"
          rsync -a /home/dev/springtail/ .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role_arn }}
          role-session-name: tempSession
          aws-region: us-east-1

      - name: Prepare Tests
        run: |
          git config --global --add safe.directory ${CI_WORKSPACE}
          # Override some settings in the config file
          .github/workflows/scripts/merge_system_settings.py system.json.settings ${SYSTEM_SETTINGS_OVERRIDE} system.json.test

          mkdir -p /opt/springtail/pids
          # Make sure we are using the correct config for Redis
          /usr/bin/redis-server /etc/redis/redis.conf --daemonize yes
          
          # Copy over the fdw_config file to the designated location
          conf_file=/etc/postgresql/16/main/postgresql.conf
          fdw_config_file_path=$(grep -E "^springtail_fdw.config_file_path" $conf_file | awk '{print $3}' | tr -d "'")
          mkdir -p $(dirname $fdw_config_file_path)
          cp system.json.test $fdw_config_file_path
          
          ln -s /home/dev/debug debug
          ln -s /home/dev/release release
          ln -s /home/dev/install install
          ln -s /home/dev/external external
          
          # Set the build dir to ../../$CI_BUILD_TYPE in test_runner_config.yaml
          sed -i -e "s|^build_dir: .*|build_dir: ../../${CI_BUILD_TYPE}|" python/testing/test_runner_config.yaml

      - name: Rebuild
        if: inputs.reuse_code == false
        run: |
          cd ${CI_BUILD_TYPE}
          make -j${NUM_PROCS} 
          cd ..

      - name: Prepare shared Docker network
        run: |
          docker network create ci_net || true
          docker network connect ci_net $(hostname)  

      - name: Start Postgres (Primary Database)
        run: |
          docker volume create pgdata 2>/dev/null || true
          docker run -d \
            --name pg16 \
            --restart unless-stopped \
            --network ci_net \
            -p 5432:5432 \
            -e POSTGRES_USER=springtail \
            -e POSTGRES_PASSWORD=springtail \
            -e POSTGRES_DB=springtail \
            -v pgdata:/var/lib/postgresql/data \
            postgres:16 \
            postgres -c wal_level=logical \
            -c max_wal_senders=10 \
            -c max_replication_slots=10 \
            -c max_connections=100 \
            -c max_prepared_transactions=64
          
          # Wait for Postgres to be ready
          if ! timeout 15s bash -c '
            until PGPASSWORD=springtail psql -h pg16 -U springtail -d postgres -c "select 1" >/dev/null 2>&1; do
            echo "Waiting for Postgres to be ready..."
            sleep 3
            done
            '; then
            echo "Postgres did not become ready within 15s" >&2
            exit 1
          fi
          # Reset primary db
          PGPASSWORD=springtail psql -h pg16 -U springtail -d postgres -c "DROP DATABASE IF EXISTS springtail;"
          PGPASSWORD=springtail psql -h pg16 -U springtail -d postgres -c "CREATE DATABASE springtail;"
          
          # Starts FDW Postgres
          service postgresql start
          sleep 4

      - name: Run performance test
        id: run-test
        run: |
          cd python/testing
          python3 springtail.py -f ../../system.json.test --load-redis --build-dir ../../${CI_BUILD_TYPE}

          cd ../performance

          _LOG_FLAG="failed"
          # Run performance tests
          python3 performance_runner.py -c performance_config.yaml 2>&1 | tee tmplog

          # Grab the success/failure status of the performance tests
          if [ $? -eq 0 ] 
          then 
            _LOG_FLAG="succeeded"
          fi
          
          # Grab the short SHA
          _LOG_SHA=$(echo $GITHUB_LATEST_SHA | cut -c1-7)
          
          # Upload performance test logs
          _TIMESTAMP=$(date +%s)
          log_file="performance-test-${_LOG_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.log" 
          log_s3_key="${S3_LOGS_PREFIX_FULL}/${log_file}"
          aws s3 cp tmplog $log_s3_key
          echo "*** Performance Test Log S3 Key: $log_s3_key"
          rm -f tmplog
          echo "test_log_s3_uri=$log_s3_key" >> $GITHUB_OUTPUT

          # Go back to the testing folder to use the springtail.py to dump the logs
          cd ../testing

          # Springtail service logs
          springtail_log_file="springtail-performance-${_LOG_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.tar.gz"
          output=$(python3 springtail.py --dump -f ../../system.json.test -b ../../${CI_BUILD_TYPE}})
          log_dump_file_name=$(echo $output | cut -f2 -d':' | xargs | head -1)
          springtail_log_s3_key="${S3_LOGS_PREFIX_FULL}/${springtail_log_file}"
          aws s3 cp $log_dump_file_name $springtail_log_s3_key
          echo "*** Springtail Log S3 Key: $springtail_log_s3_key"
          rm -f $log_dump_file_name
          echo "springtail_log_s3_uri=$springtail_log_s3_key" >> $GITHUB_OUTPUT

          if [ "$_LOG_FLAG" = "failed" ]; then
            echo "*** Performance test failed"
            exit 1
          fi
          echo "*** Finished running performance tests"
