# A reusable workflow that runs tests on the code.
name: Test

on:
  workflow_call:
    inputs:
      builder_image_version_tag:
        description: 'The image version tag for the base builder to pull.'
        type: string
        required: true
    secrets:
      aws_role_arn:
        description: "The ARN of the role to assume."
        required: true
      aws_ecr_docker_password:
        description: "The password for the ECR docker registry."
        required: true

jobs:
  test:
    name: test
    runs-on: warp-ubuntu-latest-arm64-4x-spot
    container:
      image: ${{ inputs.builder_image_version_tag }}
      credentials:
        username: AWS
        password: ${{ secrets.aws_ecr_docker_password }}

    env:
      VCPKG_FORCE_SYSTEM_BINARIES: 1
      DOCKER: 1
      ZIC: true
      USER: root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install-aws-cli-action
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2                         # default
          verbose: false                     # default
          arch: arm64

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role_arn }}
          role-session-name: tempSession
          aws-region: us-east-1

      - name: Prepare Tests
        run: |
          git config --global --add safe.directory /__w/springtail/springtail
          cp system.json.settings system.json.test
          mkdir -p /opt/springtail/pids
          service redis-server start

      - name: Build
        run: |
          ./clean.sh
          ./debug.sh -j 4

      - name: Prepare DB for Unit Tests
        run: |
          service postgresql start
          USER_EXISTS=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='springtail'")
          if [ "$USER_EXISTS" != "1" ]; then
            sudo -u postgres psql -c "CREATE USER springtail WITH PASSWORD 'springtail' SUPERUSER LOGIN" 
          fi
          sudo -u postgres psql -c "CREATE DATABASE springtail WITH OWNER springtail"

      - name: Run Unit Tests
        run: |
          cd python/testing
          python3 springtail.py -f ../../system.json.test --load-redis --build-dir ../../debug
          cd ../../debug
          log_file="unit-test-$(date +%s).log" 
          make test ARGS="--output-junit unit-test-report.xml --output-on-failure --verbose" 2>&1 | tee $log_file
          unit_test_log_s3key="s3://devsupport.springtail.internal/testlogs/$(date +"%Y/%m/%d/%H")/$log_file"
          aws s3 cp "$log_file" "$unit_test_log_s3key"
          echo "*** Unit Test Log S3 Key: $unit_test_log_s3key"

      - name: Cleanup Unit Test
        if: success() || failure()      # run this step even if previous step failed
        run: |
          # Drop the springtail database 
          sudo -u postgres psql -c "DROP DATABASE springtail"
          service postgresql stop

      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()      # run this step even if previous step failed
        with:
          name: Unit Tests             # Name of the check run which will be created
          path: ./debug/unit-test-report.xml
          reporter: java-junit
          badge-title: 'unit tests'

      - uses: actions/upload-artifact@v4
        if: success() || failure()      # run this step even if previous step failed
        with:
          name: 'Unit Test Logs'
          path: debug/unit-test-*.log

      - name: Create Superuser for test
        if: success() || failure()      # run this step even if previous step failed
        run: |
          service postgresql start
          USER_EXISTS=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='springtail'")
          if [ "$USER_EXISTS" != "1" ]; then
            sudo -u postgres psql -c "CREATE USER springtail WITH PASSWORD 'springtail' SUPERUSER LOGIN" 
          fi
          service postgresql stop

      - name: Run Integration Tests
        if: success() || failure()      # run this step even if previous step failed
        run: |
          cd python/testing
          service postgresql start
          ./startup.sh -s data_init.sql
          
          log_file="integration-test-$(date +%s).log" 
          python3 test_runner.py -c config.yaml -j /__w/springtail/springtail/integration-test-report.xml 2>&1 | tee $log_file
          integration_test_log_s3key="s3://devsupport.springtail.internal/testlogs/$(date +"%Y/%m/%d/%H")/$log_file"
          aws s3 cp "$log_file" "$integration_test_log_s3key"
          echo "*** Integration Test Log S3 Key: $integration_test_log_s3key"

      - name: Integration Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()                         # run this step even if previous step failed
        with:
          name: Integration Tests (test_runner)            # Name of the check run which will be created
          path: ./integration-test-report.xml
          reporter: java-junit
          badge-title: 'integration tests'

      - uses: actions/upload-artifact@v4
        if: success() || failure()      # run this step even if previous step failed
        with:
          name: 'Integration Test Logs'
          path: ./python/testing/integration-test-*.log