# A reusable workflow that runs tests on the code.
name: Test

on:
  workflow_call:
    inputs:
      builder_image_version_tag:
        description: 'The image version tag for the base builder to pull.'
        type: string
        required: true
      num_procs:
        description: 'The number of processes to use for the build.'
        type: string
        default: "4"
    secrets:
      aws_role_arn:
        description: "The ARN of the role to assume."
        required: true
      aws_ecr_docker_password:
        description: "The password for the ECR docker registry."
        required: true

jobs:
  test:
    name: test
    runs-on: warp-ubuntu-latest-arm64-4x
    timeout-minutes: 60
    container:
      image: ${{ inputs.builder_image_version_tag }}
      credentials:
        username: AWS
        password: ${{ secrets.aws_ecr_docker_password }}

    env:
      VCPKG_FORCE_SYSTEM_BINARIES: 1
      VCPKG_ROOT: /home/dev/external/vcpkg
      DOCKER: 1
      ZIC: true
      USER: root
      PYTHONUNBUFFERED: 1
      GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_LATEST_SHA: ${{ github.event.pull_request.head.sha }}
      NUM_PROCS: ${{ inputs.num_procs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role_arn }}
          role-session-name: tempSession
          aws-region: us-east-1

      - name: Prepare Tests
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          # Turns off the OTEL in the system.json.settings
          jq '.otel.enabled = false' system.json.settings > tmp.json && mv tmp.json system.json.settings
          # Replace the correct `springtail` code directory
          sed -i -e "s|/home/dev/springtail|${GITHUB_WORKSPACE}|g" system.json.settings
          cp system.json.settings system.json.test
          mkdir -p /opt/springtail/pids
          service redis-server start
          
          # Copies over the fdw_config file to the designated location
          conf_file=/etc/postgresql/16/main/postgresql.conf
          fdw_config_file_path=$(grep -E "^springtail_fdw.config_file_path" $conf_file | awk '{print $3}' | tr -d "'")
          mkdir -p $(dirname $fdw_config_file_path)
          cp system.json.settings $fdw_config_file_path

      - name: Build
        run: |
          ln -s /home/dev/external external
          ./debug.sh -j ${NUM_PROCS}

      - name: Prepare DB for Unit Tests
        run: |
          service postgresql start
          USER_EXISTS=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='springtail'")
          if [ "$USER_EXISTS" != "1" ]; then
            sudo -u postgres psql -c "CREATE USER springtail WITH PASSWORD 'springtail' SUPERUSER LOGIN" 
          fi
          sudo -u postgres psql -c "CREATE DATABASE springtail WITH OWNER springtail"
          # Create triggers
          sudo -u postgres psql -d springtail -f /__w/springtail/springtail/scripts/triggers.sql

      - name: Run Unit Tests
        run: |
          cd python/testing
          python3 springtail.py -f ../../system.json.test --load-redis --build-dir ../../debug
          cd ../../debug
          
          set +e
          _LOG_FLAG="succeeded"
          # Per SPR-501: break upon test failures - "--gtest_break_on_failure"
          make test ARGS="--output-junit unit-test-report.xml --output-on-failure --verbose --stop-on-failure" 2>&1 | tee tmplog
          # Grab the success/failure status of the unit tests
          if [ $? -ne 0 ] || !  grep -qE "100% tests passed" tmplog
          then 
            _LOG_FLAG="failed"
          fi
          # List the open listening ports and processes info after tests are done
          echo "==== Listening Ports ===="
          netstat -tulnp
          # Show the full launching command of each
          netstat -tulnp | awk '{print $7}' | grep -o '[0-9]*' | while read pid; do
            cmd=$(ps -p $pid -o args=)
            echo "$pid - $cmd"
          done

          # Grab the current PR ID
          _LOG_PR_ID="${GITHUB_EVENT_PULL_REQUEST_NUMBER}"
          # Grab the short SHA
          _LOG_SHA=$(echo $GITHUB_LATEST_SHA | cut -c1-7)
          
          _TIMESTAMP=$(date +"%Y-%m-%d-%H-%M-%S")
          log_file="unit-test-${_LOG_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.log.tar.gz" 
          tar zcvf $log_file tmplog
          rm tmplog
          unit_test_log_s3key="s3://devsupport.springtail.internal/testlogs/${_LOG_PR_ID}/$log_file"
          
          aws s3 cp "$log_file" "$unit_test_log_s3key"
          echo "*** Unit Test Log S3 Key: $unit_test_log_s3key"
          
          # Fail eventually
          if [ "$_LOG_FLAG" = "failed" ]; then
            exit 1
          fi

      - name: Cleanup Unit Test
        if: success() || failure()      # run this step even if previous step failed
        run: |
          # Drop the springtail database 
          sudo -u postgres psql -c "DROP DATABASE springtail"
          service postgresql stop

      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()      # run this step even if previous step failed
        with:
          name: Unit Tests             # Name of the check run which will be created
          path: ./debug/unit-test-report.xml
          reporter: java-junit

      - uses: actions/upload-artifact@v4
        if: success() || failure()      # run this step even if previous step failed
        with:
          name: 'Unit Test Logs'
          path: debug/unit-test-*.log.tar.gz

      - name: Create Superuser for test
        if: success() || failure()      # run this step even if previous step failed
        run: |
          service postgresql start
          USER_EXISTS=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='springtail'")
          if [ "$USER_EXISTS" != "1" ]; then
            sudo -u postgres psql -c "CREATE USER springtail WITH PASSWORD 'springtail' SUPERUSER LOGIN" 
          fi
          service postgresql stop

      - name: Run Integration Tests
        if: success() || failure()      # run this step even if previous step failed
        run: |
          cd python/testing
          service postgresql start
          ./startup.sh -s data_init.sql

          set +e
          _LOG_FLAG="succeeded"          
          python3 test_runner.py -c config.yaml -j /__w/springtail/springtail/integration-test-report.xml 2>&1 | tee tmplog
          # Grab the success/failure status of the integration tests
          if [ $? -ne 0 ] || grep -qE "Tests failed: [1-9][0-9]*" tmplog
          then 
            _LOG_FLAG="failed"
          fi
          # Grab the current PR ID
          _LOG_PR_ID="${GITHUB_EVENT_PULL_REQUEST_NUMBER}"
          # Grab the short SHA
          _LOG_SHA=$(echo $GITHUB_LATEST_SHA | cut -c1-7)
          
          _TIMESTAMP=$(date +"%Y-%m-%d-%H-%M-%S")
          log_file="integration-test-${_LOG_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.log.tar.gz" 
          tar zcvf $log_file tmplog
          rm tmplog
          
          # Integration test log
          integration_test_log_s3key="s3://devsupport.springtail.internal/testlogs/${_LOG_PR_ID}/$log_file"
          aws s3 cp "$log_file" "$integration_test_log_s3key"
          echo "*** Integration Test Log S3 Key: $integration_test_log_s3key"

          # Only upload Springtail logs if the _LOG_FLAG is 'failed'
          if [ "$_LOG_FLAG" = "failed" ]; then
            # Springtail service log
            echo "Integration test failed, uploading Springtail logs..."
            springtail_log_file="springtail-${_LOG_SHA}-${_LOG_FLAG}-${_TIMESTAMP}.tar.gz"
            output=$(python3 springtail.py --dump -f ../../system.json.test -b ../../debug)
            fname=$(echo $output  | cut -f2 -d':' | xargs | head -1)
            mv $fname $springtail_log_file
            springtail_log_s3key="s3://devsupport.springtail.internal/testlogs/${_LOG_PR_ID}/${springtail_log_file}"
            aws s3 cp "$springtail_log_file" "$springtail_log_s3key"
            echo "*** Springtail Log S3 Key: $springtail_log_s3key"
          fi
          
          # Fail eventually
          if [ "$_LOG_FLAG" = "failed" ]; then
            exit 1
          fi

      - name: Integration Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()                         # run this step even if previous step failed
        with:
          name: Integration Tests (test_runner)            # Name of the check run which will be created
          path: ./integration-test-report.xml
          reporter: java-junit

      - uses: actions/upload-artifact@v4
        if: success() || failure()      # run this step even if previous step failed
        with:
          name: 'Integration Test Logs'
          path: ./python/testing/integration-test-*.log.tar.gz

      - uses: actions/upload-artifact@v4
        if: success() || failure()      # run this step even if previous step failed
        with:
          name: 'Springtail Logs'
          path: ./python/testing/springtail-*.tar.gz
